kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: quay-ldap-demo
networking:
  apiServerPort: 6443
  apiServerAddress: 127.0.0.1
  podSubnet: "10.250.0.0/16"
  serviceSubnet: "10.32.0.0/16"
nodes:
- role: control-plane
  image: docker.io/kindest/node:v1.26.0
  extraPortMappings:
  - containerPort: 30389
    hostPort: 389
    listenAddress: 0.0.0.0
  - containerPort: 30636
    hostPort: 636
  - containerPort: 30080
    hostPort: 80
    listenAddress: 0.0.0.0
  - containerPort: 30443
    hostPort: 443
    listenAddress: 0.0.0.0
- role: worker
  image: docker.io/kindest/node:v1.26.0
- role: worker
  image: docker.io/kindest/node:v1.26.0

